[project]
name = "hovermodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "open3d",
    "numpy"
]

[tool.setuptools]
py-modules = ["main", "test_demo"]
